#!/bin/bash

pony="$(cd -P $(dirname "$1") && pwd)/${1##*/}"
palette="$PONYSAY_KMS_PALETTE"
[[ "$PONYSAY_KMS_PALETTE_CMD" = "" ]] || palette=$("$PONYSAY_KMS_PALETTE_CMD")

if [[ ! -f "$pony" ]]; then
    echo -e '\e[01;31mGo buck yourself\e[21;39m'
elif [[ ! "$TERM" = "linux" ]] && [[ ! "$TERM" = "-linux-" ]]; then
    cat $pony
else
    if [[ "$palette" = "" ]]; then
        palettefile="norm"
    else
	palettefile=$(sed -e 's/]P//g' <<<$palette)
    fi
    
    kmsponies="/var/cache/kmsponies4ponysay/kmsponies/"$palettefile
    kmspony="$kmsponies$pony"
    
    if [[ ! -f "$kmspony" ]]; then
	protokmsponies="/var/cache/kmsponies4ponysay/protokmsponies"
	protokmspony="$protokmsponies$pony"
	
	if [[ ! -f "$protokmspony" ]]; then
	    mkdir -p "$(dirname "$protokmspony")"
	    ponysay2ttyponysay < "$pony" > "$protokmspony"
	fi
	
	mkdir -p "$(dirname "$kmspony")"
	tty2colourfultty -e -p "$palette" < "$protokmspony" > "$kmspony"
    fi
    
    cat "$kmspony"
fi

