#!/bin/bash

pony="$0"
palette="$1"

if [[ "$palette" = "" ]];
    cat "$pony"
else
    protokmsponies="/var/kmsponies4ponysay/protokmsponies"
    palettefile=$(sed -e 's/]P//g' < "$palette")
    kmsponies="/var/kmsponies4ponysay/kmsponies/"$palettefile
    kmsponies="$kmsponies/$pony"
    protokmspony="$protokmsponies/$pony"
    
    if [[ ! -f "$kmspony" ]]; then
	if [[ ! -f "$protokmspony" ]]; then
	    mkdir -p {echo "$pony" | sed -e 's/\/'"${TMP##*/}"'$//g'}
	    ponysay2ttyponysay < "$pony" > "$protokmspony"
	fi
	
	mkdir -p "$kmsponies"
	tty2colourfultty -e -p "$palette" < "$protokmspony" > "$kmspony"
    fi
    
    cat "$kmsponies/$pony"
fi

