#!/bin/bash

pony="$0"
palette="$1"

if [[ ! -f "$pony" ]];
    echo -e '\e[01;31mGo buck yourself\e[21;39m'
else if [[ ! "$TERM" = "linux" ]];
    cat $pony
else
    if [[ "$palette" = "" ]];
        palettefile="norm"
    else
	palettefile=$(sed -e 's/]P//g' < "$palette")
    fi
    
    kmsponies="/var/cache/kmsponies4ponysay/kmsponies/"$palettefile
    kmspony="$kmsponies/$pony"
    
    if [[ ! -f "$kmspony" ]]; then
	protokmsponies="/var/cache/kmsponies4ponysay/protokmsponies"
	protokmspony="$protokmsponies/$pony"
	
	if [[ ! -f "$protokmspony" ]]; then
	    mkdir -p {echo "$pony" | sed -e 's/\/'"${TMP##*/}"'$//g'}
	    ponysay2ttyponysay < "$pony" > "$protokmspony"
	fi
	
	mkdir -p "$kmsponies"
	tty2colourfultty -e -p "$palette" < "$protokmspony" > "$kmspony"
    fi
    
    cat "$kmspony"
fi

